<?php

/**
 * @file
 * Functional hooks and callbacks.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function novatest_theme($existing, $type, $theme, $path) {
  return [
    'rental_page' => [
      'variables' => [
        'filter_form' => '',
        'list' => '',
        'pager' => '',
      ],
    ],
    'rental_list' => [
      'variables' => [
        'rentals' => [],
      ],
    ],
    'rental_item' => [
      'variables' => [
        'item' => FALSE,
        'picture' => '',
        'headline' => '',
        'type_name' => '',
        'type' => '',
        'price' => '',
        'country' => '',
        'bedrooms' => 0,
        'beds' => 0,
        'baths' => 0,
        'children' => 0,
        'adults' => 0,
        'pets' => FALSE,
        'rating' => 0,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function novatest_preprocess_rental_item(&$variables) {
  /** @var \Drupal\novatest\Entity\Rental $rental */
  $rental = $variables['item'];

  if ($pic = $rental->getPicture()) {
    $variables['picture'] = [
      '#theme' => 'image',
      '#uri' => UrlHelper::stripDangerousProtocols($pic),
    ];
  }

  $variables['headline'] = $rental->getHeadline();
  $variables['type_name'] = $rental->getPropTypeName();
  $variables['type'] = $rental->getPropType();

  if ($prices = $rental->getPrices()) {
    $variables['price_list'] = [
      '#theme' => 'item_list',
      '#title' => t('Prices'),
      '#items' => [],
    ];

    foreach ($prices as $price) {
      foreach ($price as $key => $value) {
        $variables['price_list']['#items'][] = Html::escape($key) . ': ' . Html::escape($value);
      }
    }
  }

  $variables['country'] = $rental->getCountryName();
  $variables['bedrooms'] = $rental->getBedrooms();
  $variables['beds'] = $rental->getNumberOfBeds();
  $variables['baths'] = $rental->getBathrooms();
  $variables['children'] = $rental->getChildren();
  $variables['adults'] = $rental->getAdults();
  $variables['pets'] = $rental->getPets() ? t('Yes') : t('No');
  $variables['rating'] = $rental->getRating();
}
